services:
  rails_backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rails_backend
    ports:
      - "3000:3000" # Expose Rails default port
    volumes:
      - .:/app # Mount the current directory to the container's /app
    environment:
      RAILS_ENV: development
      DB_HOST: mysql # Use the MySQL service for the database
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      - mysql
      - mongo
      - postgres

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306" # Expose MySQL default port
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails_db
      MYSQL_USER: rails_user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017" # Expose MongoDB default port
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432" # Expose PostgreSQL default port
    environment:
      POSTGRES_USER: rails_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mysql_data:
  mongo_data:
  postgres_data: